# Business-type configuration for adaptive DPR templates
# Each business category gets specific: cost labels, equipment lists,
# process steps, facility layouts, and department structures.


def detect_business_category(btype: str) -> str:
    """Detect specific business category from business_type string."""
    bt = btype.lower()
    if any(k in bt for k in ("logistic", "transport", "courier", "freight", "shipping", "delivery", "fleet", "cargo", "moving", "supply chain")):
        return "logistics"
    if any(k in bt for k in ("it", "software", "tech", "digital", "app", "web", "saas", "cloud", "data", "cyber")):
        return "it"
    if any(k in bt for k in ("consult", "advisory", "legal", "audit", "accounting", "ca ", "architect", "design", "agency", "marketing")):
        return "consulting"
    if any(k in bt for k in ("trad", "retail", "shop", "store", "e-commerce", "ecommerce", "wholesale", "distribution", "import", "export")):
        return "trading"
    if any(k in bt for k in ("health", "hospital", "clinic", "medical", "pharma", "diagnostic", "lab", "dental", "pathology")):
        return "healthcare"
    if any(k in bt for k in ("educat", "school", "college", "training", "coaching", "tutor", "institute", "academy")):
        return "education"
    if any(k in bt for k in ("hotel", "hospit", "tourism", "travel", "resort", "motel", "guest", "homestay", "lodge")):
        return "hospitality"
    if any(k in bt for k in ("food", "restaurant", "cafe", "catering", "bakery", "sweet", "dairy", "kitchen", "canteen")):
        return "food"
    if any(k in bt for k in ("service", "staffing", "finance", "fintech", "insurance", "real estate", "property")):
        return "services"
    return "manufacturing"


BIZ_CONFIG = {
    "logistics": {
        "asset_label": "Vehicles & Fleet Equipment",
        "asset_line": "Vehicles & Fleet Equipment",
        "process_label": "Logistics Operations Flow",
        "facility_label": "Warehouse / Office",
        "dept_prod": "Fleet & Operations Department",
        "worker": "Drivers & Logistics Staff",
        "helper": "Loaders & Helpers",
        "cost_labels": [
            ("Warehouse / Godown Lease", "land_and_site"),
            ("Office & Warehouse Setup", "building_civil"),
            ("Vehicles & Fleet", "plant_machinery"),
            ("GPS, IT & Tracking Systems", "misc_fixed_assets"),
            ("Licenses, Permits & Insurance", "preoperative_expenses"),
            ("Contingency", "contingency"),
            ("Working Capital", "working_capital_margin"),
        ],
        "equipment_list": [
            "| 1 | Commercial Vehicles (Trucks/Vans) | As needed | Tata/Ashok Leyland | Based on fleet size |",
            "| 2 | GPS & Fleet Tracking System | 1 Set | Branded | 2,00,000 |",
            "| 3 | Loading & Unloading Equipment | 1 Lot | Standard | 1,50,000 |",
            "| 4 | Weighing Scales & Measuring | 1 Set | Calibrated | 50,000 |",
            "| 5 | Warehouse Racking & Shelving | 1 Lot | Industrial Grade | 3,00,000 |",
            "| 6 | Packaging & Strapping Machines | 1 Set | Semi-auto | 1,00,000 |",
            "| 7 | Computers, Printers & Software | 1 Lot | Branded | 2,00,000 |",
            "| 8 | Communication & Networking | 1 Lot | Standard | 1,00,000 |",
        ],
        "process_steps": [
            "1. **Order Booking** -> Client order receipt, route planning, and scheduling",
            "2. **Pickup / Collection** -> Goods collection from sender with documentation",
            "3. **Sorting & Consolidation** -> Warehouse sorting by destination and priority",
            "4. **Loading & Dispatch** -> Fleet loading, manifest generation, and dispatch",
            "5. **In-Transit Tracking** -> Real-time GPS tracking and status updates",
            "6. **Last-Mile Delivery** -> Final delivery to consignee with POD",
            "7. **Documentation & Billing** -> Invoice generation, payment collection, and reporting",
        ],
        "facility_layout": [
            "- **Loading/Unloading Bay**: 30% — truck parking and goods handling area",
            "- **Storage/Godown Area**: 30% — racking, sorting, and consolidation",
            "- **Vehicle Parking**: 15% — fleet parking and minor maintenance",
            "- **Operations Office**: 10% — dispatch, tracking, and coordination",
            "- **Documentation Room**: 10% — billing, records, and client service",
            "- **Staff Area & Utilities**: 5% — restrooms, pantry, and security cabin",
        ],
        "infra_power": "Single-phase commercial connection with UPS backup",
    },
    "it": {
        "asset_label": "IT Infrastructure & Software",
        "asset_line": "IT Infrastructure & Software",
        "process_label": "Software Development / IT Service Process",
        "facility_label": "Office Space",
        "dept_prod": "Engineering & Development Department",
        "worker": "Software Engineers & Developers",
        "helper": "QA Testers & Support Staff",
        "cost_labels": [
            ("Office Lease & Deposit", "land_and_site"),
            ("Office Interiors & Furnishing", "building_civil"),
            ("IT Infrastructure & Software", "plant_machinery"),
            ("Furniture, Fixtures & Misc.", "misc_fixed_assets"),
            ("Company Registration & Licenses", "preoperative_expenses"),
            ("Contingency", "contingency"),
            ("Working Capital", "working_capital_margin"),
        ],
        "equipment_list": [
            "| 1 | Developer Workstations/Laptops | As per team | Dell/Lenovo/Apple | Based on team |",
            "| 2 | Servers & Cloud Infrastructure | 1 Setup | AWS/Azure/GCP | 3,00,000 |",
            "| 3 | Software Licenses (IDE, Tools) | 1 Lot | JetBrains/MS/Adobe | 2,00,000 |",
            "| 4 | Networking Equipment | 1 Set | Cisco/TP-Link | 1,00,000 |",
            "| 5 | UPS & Power Backup | 1 Set | APC/Luminous | 80,000 |",
            "| 6 | Office Furniture (Ergonomic) | 1 Lot | Branded | 3,00,000 |",
            "| 7 | Conference Room AV Equipment | 1 Set | Logitech/Poly | 1,50,000 |",
            "| 8 | Security & Access Control | 1 Lot | Standard | 70,000 |",
        ],
        "process_steps": [
            "1. **Requirement Gathering** -> Client meetings, scope documentation, and estimation",
            "2. **System Design** -> Architecture planning, wireframes, and technical design",
            "3. **Development / Coding** -> Feature implementation following agile sprints",
            "4. **Testing & QA** -> Unit testing, integration testing, and UAT",
            "5. **Deployment** -> Production deployment, monitoring, and go-live",
            "6. **Maintenance & Support** -> Bug fixes, updates, and client support",
            "7. **Feedback & Iteration** -> Continuous improvement and new features",
        ],
        "facility_layout": [
            "- **Development Floor**: 40% — developer workstations with standing desks",
            "- **Conference / Meeting Rooms**: 15% — client meetings and video calls",
            "- **Server / Networking Room**: 5% — servers, switches, and backup systems",
            "- **Management Offices**: 15% — CEO, CTO, HR, and accounts",
            "- **Recreation / Break Area**: 10% — pantry, games, and relaxation zone",
            "- **Reception & Common Area**: 15% — visitor lobby and collaborative space",
        ],
        "infra_power": "Single-phase with dedicated UPS and internet backup",
    },
    "consulting": {
        "asset_label": "Office Equipment & Professional Tools",
        "asset_line": "Office Equipment & Professional Tools",
        "process_label": "Client Engagement Process",
        "facility_label": "Office Suite",
        "dept_prod": "Consulting & Advisory Department",
        "worker": "Consultants & Analysts",
        "helper": "Research Assistants & Admin Staff",
        "cost_labels": [
            ("Office Lease & Deposit", "land_and_site"),
            ("Office Interiors & Branding", "building_civil"),
            ("Computers, Software & Tools", "plant_machinery"),
            ("Furniture, Library & Misc.", "misc_fixed_assets"),
            ("Certifications & Professional Licenses", "preoperative_expenses"),
            ("Contingency", "contingency"),
            ("Working Capital", "working_capital_margin"),
        ],
        "equipment_list": [
            "| 1 | Laptops & Workstations | Per person | Dell/Lenovo/Apple | Based on team |",
            "| 2 | Professional Software Licenses | 1 Lot | MS Office/Zoom/CRM | 1,50,000 |",
            "| 3 | Office Furniture (Executive) | 1 Lot | Premium Branded | 3,00,000 |",
            "| 4 | Conference Room AV Setup | 1 Set | Poly/Logitech | 2,00,000 |",
            "| 5 | Printer & Documentation | 1 Set | HP/Canon | 1,00,000 |",
            "| 6 | Reference Library & Subscriptions | 1 Lot | Industry Reports | 1,00,000 |",
            "| 7 | Networking & Internet | 1 Lot | Enterprise Grade | 80,000 |",
            "| 8 | Branding & Signage | 1 Lot | Custom | 70,000 |",
        ],
        "process_steps": [
            "1. **Lead Generation** -> Marketing, referrals, and proposal submissions",
            "2. **Client Onboarding** -> NDA, scope of work, and engagement letter",
            "3. **Research & Analysis** -> Data collection and industry benchmarking",
            "4. **Strategy Development** -> Solution design and recommendations",
            "5. **Presentation & Review** -> Client presentation and iterations",
            "6. **Implementation Support** -> Handholding during execution",
            "7. **Follow-up & Retainer** -> Post-project review and ongoing advisory",
        ],
        "facility_layout": [
            "- **Consultant Workstations**: 35% — individual and team work areas",
            "- **Conference Rooms**: 20% — client meetings and presentations",
            "- **Executive Cabins**: 15% — senior partner and management offices",
            "- **Research Library**: 10% — reference materials and study area",
            "- **Reception & Waiting**: 10% — professional client-facing area",
            "- **Pantry & Utilities**: 10% — staff amenities and facilities",
        ],
        "infra_power": "Single-phase commercial connection",
    },
    "trading": {
        "asset_label": "Shop Fixtures, Display & Equipment",
        "asset_line": "Shop Fixtures, Display & Equipment",
        "process_label": "Trading & Distribution Process",
        "facility_label": "Shop / Showroom / Warehouse",
        "dept_prod": "Sales & Distribution Department",
        "worker": "Sales Executives & Shop Staff",
        "helper": "Store Boys & Delivery Staff",
        "cost_labels": [
            ("Shop / Showroom Lease & Deposit", "land_and_site"),
            ("Shop Interiors & Display Setup", "building_civil"),
            ("Display Fixtures & Equipment", "plant_machinery"),
            ("Billing System, CCTV & Misc.", "misc_fixed_assets"),
            ("Trade Licenses & GST Registration", "preoperative_expenses"),
            ("Contingency", "contingency"),
            ("Working Capital (Stock Purchase)", "working_capital_margin"),
        ],
        "equipment_list": [
            "| 1 | Display Racks & Shelving | 1 Lot | Custom/Standard | 3,00,000 |",
            "| 2 | Billing Counter & POS System | 1 Set | Branded | 1,50,000 |",
            "| 3 | CCTV & Security System | 1 Set | Hikvision/CP Plus | 1,00,000 |",
            "| 4 | Air Conditioning | As needed | Daikin/Voltas | 2,00,000 |",
            "| 5 | Computer & Accounting Software | 1 Set | Tally/Busy | 80,000 |",
            "| 6 | Delivery Vehicle | 1 No. | Used/New | 3,00,000 |",
            "| 7 | Signage & Branding | 1 Lot | LED/Flex | 1,00,000 |",
            "| 8 | Packaging Materials & Misc. | 1 Lot | Standard | 70,000 |",
        ],
        "process_steps": [
            "1. **Supplier Sourcing** -> Vendor identification, negotiation, and orders",
            "2. **Procurement & Inward** -> Goods receipt, quality check, and inventory entry",
            "3. **Storage & Inventory** -> Systematic storage with FIFO and stock management",
            "4. **Display & Merchandising** -> Product display, pricing, and promotions",
            "5. **Sales & Billing** -> Customer service, billing, and payment collection",
            "6. **Delivery / Dispatch** -> Order packing and delivery to customers",
            "7. **Returns & After-Sales** -> Return handling, warranty, and feedback",
        ],
        "facility_layout": [
            "- **Showroom / Sales Floor**: 40% — product display and customer area",
            "- **Storage / Godown**: 25% — inventory and stock storage",
            "- **Billing Counter**: 10% — cashier, POS, and customer checkout",
            "- **Office / Accounts**: 10% — management and accounting",
            "- **Loading Area**: 10% — goods receipt and dispatch",
            "- **Utilities & Restroom**: 5% — staff amenities",
        ],
        "infra_power": "Single-phase commercial connection",
    },
    "healthcare": {
        "asset_label": "Medical Equipment & Instruments",
        "asset_line": "Medical Equipment & Instruments",
        "process_label": "Patient Care Process",
        "facility_label": "Clinic / Hospital",
        "dept_prod": "Medical & Clinical Department",
        "worker": "Doctors, Nurses & Paramedics",
        "helper": "Attendants & Admin Staff",
        "cost_labels": [
            ("Premises Lease / Purchase", "land_and_site"),
            ("Clinic Interiors & Setup", "building_civil"),
            ("Medical Equipment & Instruments", "plant_machinery"),
            ("Furniture, IT System & Misc.", "misc_fixed_assets"),
            ("Medical Licenses & Registration", "preoperative_expenses"),
            ("Contingency", "contingency"),
            ("Working Capital", "working_capital_margin"),
        ],
        "equipment_list": [
            "| 1 | Diagnostic Equipment | As needed | Reputed Medical | Based on specialty |",
            "| 2 | Patient Beds & OT Setup | As needed | Hospital Grade | 5,00,000 |",
            "| 3 | Sterilization Equipment | 1 Set | Medical Grade | 2,00,000 |",
            "| 4 | HMIS / EMR Software | 1 License | Practo/Custom | 1,50,000 |",
            "| 5 | Pharmacy Setup | 1 Lot | Standard | 2,00,000 |",
            "| 6 | AC & Ventilation | 1 Lot | Medical Grade | 3,00,000 |",
            "| 7 | Generator & UPS Backup | 1 Set | Standard | 2,50,000 |",
            "| 8 | Ambulance / Vehicle | 1 No. | Force/Tata | 8,00,000 |",
        ],
        "process_steps": [
            "1. **Patient Registration** -> Reception, records, and appointment scheduling",
            "2. **Consultation** -> Doctor consultation, history, and examination",
            "3. **Diagnosis** -> Lab tests, imaging, and diagnostic evaluation",
            "4. **Treatment Plan** -> Prescription, procedure, or therapy",
            "5. **Treatment / Procedure** -> Medical treatment or surgical procedure",
            "6. **Recovery & Follow-up** -> Post-treatment care & follow-up visits",
            "7. **Billing & Discharge** -> Invoice, insurance claims, and discharge",
        ],
        "facility_layout": [
            "- **Consultation Rooms**: 25% — doctor cabins and examination rooms",
            "- **Diagnostic / Lab Area**: 20% — pathology, imaging, and testing",
            "- **Treatment / OT Room**: 20% — procedure rooms and OT",
            "- **Patient Waiting Area**: 15% — reception and waiting hall",
            "- **Pharmacy**: 10% — medicine dispensary",
            "- **Admin & Staff Area**: 10% — office, records, and staff room",
        ],
        "infra_power": "3-phase with dedicated medical-grade power backup",
    },
    "education": {
        "asset_label": "Teaching Aids & Infrastructure",
        "asset_line": "Teaching Aids & IT Equipment",
        "process_label": "Education Delivery Process",
        "facility_label": "Institute / Training Center",
        "dept_prod": "Academic & Training Department",
        "worker": "Teachers / Trainers / Faculty",
        "helper": "Administrative & Support Staff",
        "cost_labels": [
            ("Premises Lease / Rent", "land_and_site"),
            ("Classroom Interiors & Setup", "building_civil"),
            ("Teaching Aids & IT Equipment", "plant_machinery"),
            ("Furniture, Library & Misc.", "misc_fixed_assets"),
            ("Affiliation & Approvals", "preoperative_expenses"),
            ("Contingency", "contingency"),
            ("Working Capital", "working_capital_margin"),
        ],
        "equipment_list": [
            "| 1 | Smart Boards / Projectors | Per class | Branded | 2,00,000 |",
            "| 2 | Student Furniture | 1 Lot | Standard | 3,00,000 |",
            "| 3 | Computer Lab Setup | 1 Lab | Assembled/Brand | 4,00,000 |",
            "| 4 | Library Books & Shelving | 1 Lot | Various | 1,50,000 |",
            "| 5 | CCTV & Security | 1 Set | CP Plus/Hikvision | 1,00,000 |",
            "| 6 | Student Mgmt Software | 1 License | SaaS/Custom | 80,000 |",
            "| 7 | Lab Equipment (if applicable) | 1 Lot | Standard | 2,00,000 |",
            "| 8 | Branding & Signage | 1 Lot | Custom | 70,000 |",
        ],
        "process_steps": [
            "1. **Student Enrollment** -> Admission, counseling, and registration",
            "2. **Curriculum Planning** -> Syllabus design and scheduling",
            "3. **Teaching & Training** -> Classroom/online sessions and practicals",
            "4. **Assessment** -> Tests, assignments, and evaluation",
            "5. **Feedback & Improvement** -> Student feedback and refinement",
            "6. **Certification** -> Exams, results, and certificate issuance",
            "7. **Placement / Alumni** -> Career counseling and placement support",
        ],
        "facility_layout": [
            "- **Classrooms**: 40% — teaching and training rooms",
            "- **Computer / Practical Lab**: 15% — hands-on learning space",
            "- **Library / Study Area**: 10% — reading and research",
            "- **Administrative Office**: 15% — management, accounts, records",
            "- **Reception & Waiting**: 10% — student and parent area",
            "- **Restrooms & Utilities**: 10% — washrooms, pantry, storage",
        ],
        "infra_power": "Single-phase commercial connection with UPS",
    },
    "hospitality": {
        "asset_label": "Hospitality Equipment & Furnishing",
        "asset_line": "Room Furnishing & Kitchen Equipment",
        "process_label": "Guest Service Process",
        "facility_label": "Hotel / Resort / Property",
        "dept_prod": "Housekeeping & Guest Services",
        "worker": "Front Desk, Housekeeping & Kitchen Staff",
        "helper": "Bellboys, Cleaners & Support Staff",
        "cost_labels": [
            ("Property Lease / Purchase", "land_and_site"),
            ("Interior Design & Civil Works", "building_civil"),
            ("Room Furnishing & Kitchen Equipment", "plant_machinery"),
            ("Electronics, CCTV & Misc.", "misc_fixed_assets"),
            ("Licenses (FSSAI, Tourism, etc.)", "preoperative_expenses"),
            ("Contingency", "contingency"),
            ("Working Capital", "working_capital_margin"),
        ],
        "equipment_list": [
            "| 1 | Room Furniture & Bedding | Per room | Premium | Based on rooms |",
            "| 2 | Commercial Kitchen Equipment | 1 Lot | SS Commercial | 5,00,000 |",
            "| 3 | Laundry Equipment | 1 Set | Industrial | 2,00,000 |",
            "| 4 | CCTV & Security | 1 Set | Branded | 1,50,000 |",
            "| 5 | Hotel PMS Software | 1 License | Opera/Custom | 1,00,000 |",
            "| 6 | Generator & Water Treatment | 1 Set | Standard | 3,00,000 |",
            "| 7 | AC & HVAC System | Per room | Daikin/Carrier | 5,00,000 |",
            "| 8 | Signage, Branding & Website | 1 Lot | Custom | 1,50,000 |",
        ],
        "process_steps": [
            "1. **Booking & Reservation** -> Online/offline booking and confirmation",
            "2. **Guest Check-In** -> Welcome, ID verification, and room allotment",
            "3. **Room Service** -> Housekeeping, laundry, and in-room amenities",
            "4. **Food & Beverage** -> Restaurant, room service, and catering",
            "5. **Concierge Services** -> Tours, travel assistance, and requests",
            "6. **Billing & Check-Out** -> Invoice settlement and feedback",
            "7. **Review & Marketing** -> Online reviews and repeat marketing",
        ],
        "facility_layout": [
            "- **Guest Rooms**: 45% — accommodation with attached bathrooms",
            "- **Restaurant / Kitchen**: 15% — dining area and commercial kitchen",
            "- **Lobby & Reception**: 15% — check-in, lounge, and waiting",
            "- **Back Office**: 10% — management, accounts, and staff room",
            "- **Utility Areas**: 10% — laundry, storage, mechanical room",
            "- **Outdoor / Parking**: 5% — parking, garden, or terrace",
        ],
        "infra_power": "3-phase connection with full generator backup",
    },
    "food": {
        "asset_label": "Kitchen Equipment & Machinery",
        "asset_line": "Kitchen Equipment & Food Processing Machinery",
        "process_label": "Food Production & Service Process",
        "facility_label": "Kitchen / Production Unit",
        "dept_prod": "Kitchen & Production Department",
        "worker": "Chefs, Cooks & Kitchen Staff",
        "helper": "Helpers & Packaging Staff",
        "cost_labels": [
            ("Premises Lease / Purchase", "land_and_site"),
            ("Kitchen & Dining Setup", "building_civil"),
            ("Kitchen Equipment & Machinery", "plant_machinery"),
            ("Utensils, Refrigeration & Misc.", "misc_fixed_assets"),
            ("FSSAI License & Registrations", "preoperative_expenses"),
            ("Contingency", "contingency"),
            ("Working Capital (Raw Materials)", "working_capital_margin"),
        ],
        "equipment_list": [
            "| 1 | Commercial Gas Range & Oven | 1 Set | SS Commercial | 3,00,000 |",
            "| 2 | Refrigerators & Deep Freezers | As needed | Voltas/Blue Star | 2,50,000 |",
            "| 3 | Food Processing Equipment | 1 Lot | Stainless Steel | 2,00,000 |",
            "| 4 | Exhaust & Ventilation System | 1 Set | Commercial Grade | 1,50,000 |",
            "| 5 | Packaging & Sealing Machine | 1 Set | Semi-automatic | 1,00,000 |",
            "| 6 | Water Purification (RO) | 1 Set | Commercial | 50,000 |",
            "| 7 | Furniture (Tables, Chairs) | 1 Lot | Standard | 2,00,000 |",
            "| 8 | POS System & Billing | 1 Set | Branded | 80,000 |",
        ],
        "process_steps": [
            "1. **Raw Material Procurement** -> Fresh ingredients from trusted vendors",
            "2. **Quality Inspection** -> Freshness check, grading, and storage",
            "3. **Preparation & Cooking** -> Recipe-based preparation and cooking",
            "4. **Quality & Taste Check** -> Taste testing and hygiene compliance",
            "5. **Packaging / Plating** -> Hygienic packaging or elegant plating",
            "6. **Service / Delivery** -> Dine-in, takeaway, or home delivery",
            "7. **Feedback & Audit** -> Customer feedback and FSSAI compliance",
        ],
        "facility_layout": [
            "- **Main Kitchen**: 35% — cooking, preparation, and plating area",
            "- **Storage & Cold Room**: 15% — raw material and cold storage",
            "- **Dining / Seating Area**: 25% — customer seating and service",
            "- **Billing Counter**: 10% — order taking, billing, and cash",
            "- **Wash Area & Cleaning**: 10% — dishwashing and sanitization",
            "- **Staff Area & Restroom**: 5% — changing room and washrooms",
        ],
        "infra_power": "3-phase commercial connection with gas line",
    },
    "services": {
        "asset_label": "Office Equipment & Technology",
        "asset_line": "Office Equipment & Technology",
        "process_label": "Service Delivery Process",
        "facility_label": "Office / Facility",
        "dept_prod": "Operations Department",
        "worker": "Operations Staff",
        "helper": "Support Staff",
        "cost_labels": [
            ("Office Lease & Deposit", "land_and_site"),
            ("Office Interiors & Setup", "building_civil"),
            ("Equipment & Technology", "plant_machinery"),
            ("Furniture, Fixtures & Misc.", "misc_fixed_assets"),
            ("Licenses & Registrations", "preoperative_expenses"),
            ("Contingency", "contingency"),
            ("Working Capital", "working_capital_margin"),
        ],
        "equipment_list": [
            "| 1 | Computers & Workstations | 1 Lot | Branded | 5,00,000 |",
            "| 2 | Software & Licenses | 1 Lot | Various | 3,00,000 |",
            "| 3 | Networking & IT | 1 Set | Standard | 2,00,000 |",
            "| 4 | Office Furniture | 1 Lot | Branded | 3,00,000 |",
            "| 5 | Communication Systems | 1 Set | Standard | 1,50,000 |",
            "| 6 | Printing & Documentation | 1 Set | HP/Canon | 80,000 |",
            "| 7 | UPS & Power Backup | 1 Set | Standard | 70,000 |",
            "| 8 | Signage & Branding | 1 Lot | Custom | 1,00,000 |",
        ],
        "process_steps": [
            "1. **Client Acquisition** -> Lead generation, proposals, and onboarding",
            "2. **Requirement Analysis** -> Understanding client needs and scope",
            "3. **Service Planning** -> Resource allocation and scheduling",
            "4. **Service Delivery** -> Core service execution and operations",
            "5. **Quality Assurance** -> Service quality checks and feedback",
            "6. **Reporting & Billing** -> Documentation, invoicing, and follow-up",
            "7. **After-Sales Support** -> Ongoing support and relationship management",
        ],
        "facility_layout": [
            "- **Operations Area**: 40% — main service delivery workspace",
            "- **Client Meeting Rooms**: 15% — meeting and conference spaces",
            "- **Management Offices**: 15% — leadership and administration",
            "- **Staff Workstations**: 15% — employee workspace with IT",
            "- **Storage / Server Room**: 5% — equipment and infrastructure",
            "- **Utilities & Pantry**: 10% — staff amenities and common areas",
        ],
        "infra_power": "Single-phase commercial connection",
    },
    "manufacturing": {
        "asset_label": "Plant & Machinery",
        "asset_line": "Plant & Machinery",
        "process_label": "Production Process Flow",
        "facility_label": "Factory / Workshop",
        "dept_prod": "Production Department",
        "worker": "Machine Operators",
        "helper": "Helpers",
        "cost_labels": [
            ("Land & Site Development", "land_and_site"),
            ("Building & Civil Works", "building_civil"),
            ("Plant & Machinery", "plant_machinery"),
            ("Misc. Fixed Assets", "misc_fixed_assets"),
            ("Pre-operative Expenses", "preoperative_expenses"),
            ("Contingency", "contingency"),
            ("Working Capital", "working_capital_margin"),
        ],
        "equipment_list": [
            "| 1 | Primary Processing Machine | 2 | Reputed Indian | 8,00,000 |",
            "| 2 | Secondary Processing Unit | 1 | Reputed Indian | 5,00,000 |",
            "| 3 | Quality Testing Equipment | 1 Set | Imported/Indian | 3,00,000 |",
            "| 4 | Packaging Machine | 1 | Indian Make | 2,50,000 |",
            "| 5 | Material Handling | 1 Set | Indian Make | 1,50,000 |",
            "| 6 | Weighing & Measuring | 1 Set | Calibrated | 1,00,000 |",
            "| 7 | Auxiliary Equipment | 1 Lot | Various | 2,00,000 |",
            "| 8 | Electrical Installation | 1 Lot | Standard | 1,50,000 |",
        ],
        "process_steps": [
            "1. **Raw Material Procurement** -> Quality inspection and storage",
            "2. **Pre-Processing** -> Material preparation and conditioning",
            "3. **Main Processing** -> Core production/manufacturing",
            "4. **Quality Testing** -> In-process and final quality verification",
            "5. **Finishing** -> Final processing, grading, and sorting",
            "6. **Packaging** -> Professional packaging and labeling",
            "7. **Dispatch** -> Storage, logistics, and delivery",
        ],
        "facility_layout": [
            "- **Production Hall**: 60% — housing all production machinery",
            "- **Raw Material Storage**: 15% — climate-controlled storage",
            "- **Finished Goods Store**: 10% — organized storage with FIFO",
            "- **Quality Lab**: 5% — testing and inspection area",
            "- **Office & Admin**: 5% — management offices and meeting room",
            "- **Utilities Area**: 5% — DG set, compressor, water treatment",
        ],
        "infra_power": "3-phase industrial connection",
    },
}


def get_biz_config(business_type: str) -> dict:
    """Get full config dict for the detected business category."""
    cat = detect_business_category(business_type)
    return BIZ_CONFIG.get(cat, BIZ_CONFIG["manufacturing"])
